Blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('blog.urls', namespace='blog')),
]

blog/urls.py
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^artigo/(?P<artigo_id>\d+)/$', views.artigo, name='artigo'),
]

blog/models.py
from django.db import models

# Create your models here.
class Artigo(models.Model):
    class Meta:
        ordering = ('-publicacao',)

    titulo = models.CharField(max_length=100)
    conteudo = models.TextField()
    publicacao = models.DateTimeField(auto_now_add=True)

blog/views.py
from django.shortcuts import render
from django.template import RequestContext
from .models import Artigo

# Create your views here.

def index(request):
    artigos = Artigo.objects.all()
    context = {'artigos':artigos}
    return render(request, 'blog/index.html', context)

def artigo(request, artigo_id):
    art = Artigo.objects.get(id=artigo_id)
    context = {'artigo':art}
    return render(request, 'blog/artigo.html', context)

Blog/templates/base.html
{% load bootstrap3 %}

<html>
<head>
  <title>
    {% block titulo %}Blog do Alatazan{% endblock %}
  </title>

  {% bootstrap_css %}
  {% bootstrap_javascript %}

</head>
<body>
  <!--Static navbar -->
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapsed"
          data-target="#navbar" arial-expanded="false" aria-controls="navbar">
        </button>
        <a class="navbar-brand" href="{% url 'blog:index' %}">Blog do Alatazan</a>
      </div>
    </div>
  </nav>
  <div class="conteudo">
    {% block conteudo %}{% endblock %}
  </div>
  {% include "rodape.html" %}
</body>
</html>

Blog/templates/rodape.html
<div class="rodape">
  Por favor não faça contato. Obrigado pela atenção.
</div>

blog/templates/blog/artigo.html
{% extends "base.html" %}

{% block titulo %}{{ artigo.titulo }} -
{{ block.super }}{% endblock %}

{% block h1 %} {{ artigo.titulo }} {% endblock %}

{% block conteudo %}
  {{ artigo.conteudo }}
{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block conteudo %}
  {% for artigo in artigos %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          Publicado em {{artigo.publicacao|timesince}}<br/>
          <small>
            <a href="{% url 'blog:artigo' artigo_id=artigo.id %}">
              <h2>{{artigo.titulo}}</h2>
            </a>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        {{artigo.conteudo}}
      </div>
    </div>
  {% endfor %}
{% endblock %}